# FROM golang:latest
# RUN mkdir /go/src
# RUN go get -u github.com/golang/dep/cmd/dep
# ADD . /go/src
# WORKDIR /go/src
#
# RUN go build -o main .
# RUN dep ensure
# RUN go build
# CMD ["/go/src/main"]
