version: '3.4'
services:
 rabbitmq:
    image:  rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
 producer:
    build:  './rmq-producer'
    ports:
      - "8080:8080"
    environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672
      - spring.rabbitmq.username=guest
      - spring.rabbitmq.password=guest
      - jsa.rabbitmq.queue=rmq-queue
      - jsa.rabbitmq.exchange=rmq-exchange
      - jsa.rabbitmq.routingkey=rmq-routingkey
      - spring.main.allow-bean-definition-overriding=true
    depends_on:
      - rabbitmq
 consumer:
    build : './rmq-consumer'
    environment:
      - rabbithost=rabbitmq
    depends_on:
      - rabbitmq

# When using docker-compose up, Consumer container starts before RabbitMQ, which causes the connection failure.
# solutions: restart: on-failure, healthcheck:start_period(docker compose 3.4+) or https://github.com/ufoscout/docker-compose-wait
